name: Test

# Controls when the action will run. 
on:
  pull_request:
    paths: endpoint/**/*
    
env:
  GITHUB_REF: ${{ github.ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          echo "Hello from $TEST"
        env:
          TEST: ${{ github.sha:0:3}}
        
  build:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build
        run: |
          echo "This should only run when we are pushing commit to master"
          
  production:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Production
        
        run: |
          echo "This should only trigger when we are tagging and creating release"
          
