name: Test

# Controls when the action will run. 
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: andersinno/kolga-setup-action@v3
        
      - name: "Testing out"
        run: |
          echo "Hello from $K8S_ADDITIONAL_HOSTNAMES"
        
      
          
