name: Test

on:
  ["push"]


jobs:
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          apt-get update -y
